# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEAS', '0002_studentproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('student_name', models.CharField(max_length=128, null=True)),
                ('project_id', models.IntegerField()),
                ('score', models.IntegerField()),
            ],
        ),
    ]
