# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CEAS', '0003_resultalgorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='from_what_areas_do_you_wish_to_recruit_student',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ASP', 'Aerospace Engineering'), ('AM', 'Applied Mathematics'), ('AE', 'Architectural Engineering'), ('CE', 'Chemical Engineering'), ('CBE', 'Chemical and Biological Engineering'), ('CVE', 'Civil Engineering'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ECE', 'Electrical and Computer Engineering'), ('EP', 'Engineering Physics'), ('ENVE', 'Environmental Engineering'), ('EPL', 'Engineering Plus'), ('ME', 'Mechanical Engineering')], default='CS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='secondary_faculty_department',
            field=models.CharField(blank=True, choices=[('ASP', 'Aerospace Engineering'), ('AM', 'Applied Mathematics'), ('AE', 'Architectural Engineering'), ('CE', 'Chemical Engineering'), ('CBE', 'Chemical and Biological Engineering'), ('CVE', 'Civil Engineering'), ('CS', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ECE', 'Electrical and Computer Engineering'), ('EP', 'Engineering Physics'), ('ENVE', 'Environmental Engineering'), ('EPL', 'Engineering Plus'), ('ME', 'Mechanical Engineering')], default='CS', max_length=50, null=True),
        ),
    ]
