# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-18 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CEAS', '0008_auto_20161118_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fifthChoice',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstChoice',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='fourthChoice',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='secondChoice',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='thirdChoice',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
